"""empty message

Revision ID: 7c57fc1adbfc
Revises: 
Create Date: 2023-09-28 22:50:28.260752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c57fc1adbfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_file', sa.String(length=128), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('highlighted_code', sa.Text(), nullable=True),
    sa.Column('style_definitions', sa.Text(), nullable=True),
    sa.Column('style_bg_color', sa.String(length=128), nullable=True),
    sa.Column('lexer', sa.String(length=64), nullable=True),
    sa.Column('current_lang', sa.String(length=64), nullable=True),
    sa.Column('style', sa.String(length=64), nullable=True),
    sa.Column('font', sa.String(length=64), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_id'), ['id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_id'))

    op.drop_table('image')
    # ### end Alembic commands ###
